### ISSUE TITLE
golang support to project?

### ISSUE THREAD

**Issue by andriisoldatenko** [adnanaziz/EPIJudge#109]
what do you think if i add support fo golang project?

**Comment by vijaykiran225** [comment]
👍  would be awesome

**Comment by tsunghsienlee** [comment]
Hi @andriisoldatenko and @vijaykiran225 ,

Really appreciate for you guys support, and we really appreciate that. We right now don't think any new language support, and it simply because we don't have enough manpower to develop that. If you look at our repository, to make EPIJudge works out of box without installation and any hassles. we have to implement the backend logic for each language. It means, we need to re-implement the whole system in goland; which is a huge effort I shall say.

However, it does not mean we are not considering golang in the future, and if one day we see golang becomes the main stream, we will definitely come back on this; in the end of day, this book and EPIJudge is trying to serve our readers!

**Comment by stefantds** [comment]
I implemented a Golang version of the EPI Judge (only testing framework, no solutions yet) using the test cases from this repo. It could be a starting point for a future support of Golang.
Feel free to give it a try. Feedback and contributions are welcome: https://github.com/stefantds/go-epi-judge
