### ISSUE TITLE
Unnecessary line in python solution of Problem 11.9 and issues with test cases

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#133]
Line no 24 https://github.com/adnanaziz/EPIJudge/blob/9b1e7e4975ec8e38327f4a05ac067bebd36cbbad/epi_judge_python_solutions/absent_value_array.py#L24 in the solution for Problem 11.9 seems to be  extraneous and not serving any purpose

We already take two copies of the stream in line 11 
`stream, stream_copy = itertools.tee(stream)` which are used to handle the two iterations over the stream, so the need of doing `stream = stream_copy` and not using `stream` later is not really clear, and maybe an extra line added by mistake.

Also a quick look at the `absent_value_array.tsv` file showed that the input set is really small compared to the one billion IP address mentioned in the question, and hence I can easily cheat the testing system by just doing  say`return 1000`. I think the test inputs for this question need a re-look as well

**Comment by deveshks** [comment]
Hi @tsunghsienlee 
Can I make a PR to fix this in the dev branch?

**Comment by tsunghsienlee** [comment]
Hi @deveshks ,

That `stream = stream_copy` is definitely redundant as my original indentation is to still iterating through `stream` in second for loop.

About the test case problem, it is actually a comprised answer here since we could not create a file with billions of integers in `.tsv` file. The idea to improve the test data is by some interesting representation of those integers, like representing the numbers are missing in a range test data defined. This definitely could be an improvement we could do in the future.

**Comment by tsunghsienlee** [comment]
FYI, the reason the issue was closed was due to my git commit on private repo fixes that.

**Comment by deveshks** [comment]
Hi @tsunghsienlee 

Understood, let me add a fix  in the dev branch as well to remove the redundant line. 

I can also see if there is an easier way to represent a billion of integers in a easier way in the tsv file and maybe update the testing accordingly

**Comment by tsunghsienlee** [comment]
The way to represent that is to represent the dual (or inverse) of that since a meaningful test data would be something that only a few are missing in billions of numbers. This requires a little bit more changes that involves the changes of the wrapper and testing logic.

**Comment by deveshks** [comment]
I think this issue can be closed now

**Comment by deveshks** [comment]
Closing this issue since it's already fixed
