### ISSUE TITLE
Python solution of problem 12.6 not utilizing the defined namedtuple

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#134]
The defined `SubArray` namedtuple at 
https://github.com/adnanaziz/EPIJudge/blob/9b1e7e4975ec8e38327f4a05ac067bebd36cbbad/epi_judge_python_solutions/smallest_subarray_covering_set.py#L8
is not being used further in the code, especially at 
https://github.com/adnanaziz/EPIJudge/blob/9b1e7e4975ec8e38327f4a05ac067bebd36cbbad/epi_judge_python_solutions/smallest_subarray_covering_set.py#L26
where indexes are being used instead

**Comment by adnanaziz** [comment]
@metopa / @tsunghsienlee , @deveshks  is right, I think this is caused by the refactoring we did to replace tuples with namedtuples, line 26 should be something like

``
if result == Subarray(start=-1, end=-1) or right - left < result.start - result-end
``
(maybe also have a static constant for Subarray(start=-1, end=-1)?)

**Comment by deveshks** [comment]
Hi @adnanaziz 

The line 26 should be something thing like `if result == Subarray(start=-1, end=-1) or right - left < result.end - result.start:` I think, since `result[1]` corresponds to the attribute `end`, and `result[0]` to `start`.

I can make a PR and fix this is in the dev branch as well

**Comment by deveshks** [comment]
I see the problem is fixed after a latest commit in dev branch, so this issue can be closed

**Comment by deveshks** [comment]
Closing this issue since it's already fixed
