### ISSUE TITLE
A solution mentioned in the book is missing for Problem 14.1

### ISSUE THREAD

**Issue by deveshks** [adnanaziz/EPIJudge#138]
The queue based solution for the problem `Test if a binary tree satisfies the BST property` which checks the violations of the BST property in a BFS manner is missing from the solution. 
I can create a PR to add the same

**Comment by tsunghsienlee** [comment]
It is designed to be listed in the book but not in judge because it is solving identical problem. For people who want to try the BFS approach, they still could use the same stub we created for the problem.

In fact, we have other problems like that, for example, the problems of dutch national flag that we have several solutions for that problem but we decided to not listed that in judge for same reason.

**Comment by deveshks** [comment]
Thank you for the explanation. So does that mean that are the judge is not open to adding some of the explicit solutions mentioned in the question like Problem 14.1?

**Comment by tsunghsienlee** [comment]
The answer is yes and no, as I said in the previous comment. You could still use the same stub to test whatever your algorithm is. Creating two problems with identical stub is meaningless. If you want to make difference, you could only achieve this by creating different test data and special mechanism to differentiate the implementations. However, since those different implementation still have identical worst case time complexities so I doubt there is any reasonable way to differentiate different implementations.

**Comment by deveshks** [comment]
Makes sense. In that case I am closing this ticket
