### ISSUE TITLE
Enhancement for The Most Visited Pages Problem

### ISSUE THREAD

**Issue by zorro786** [adnanaziz/EPIJudge#145]
"To find the k most visited pages we find the maximum element in the BST and make k - 1 calls to the predecessor function. If the tree is height-balanced, the time complexity of k - 1 calls to predecessor is 0(k + log m)."

The k most visited pages can be found in O(k) time using descendingIterator().

**Comment by tsunghsienlee** [comment]
Not very sure what you want to express, do you mean descendingIterator() is O(1) each call? If that is what you mean, you might want to check the problem "Compute the successor" as descendingIterator() is the mirror of that.

The amortized time complexity of that is O(1) but in the worst case, in a height-balanced tree, it would be O(logm); so that is the reason the whole complexity is O(k + logm).
