### ISSUE TITLE
even_odd_array solution wont work if array contains all odd numbers in python

### ISSUE THREAD

**Issue by sagarsavla** [adnanaziz/EPIJudge#178]
even_odd_array solution wont work if array contains all odd numbers in python

Try running for A = [1,3,5,7] you will get [3,5,7,1]

**Comment by deveshks** [comment]
Can you explain why do you think `[3,5,7,1]` is not the correct solution for `A = [1,3,5,7]` ? 

The question states that `Your input is an array of integers, and you have to reorder its entries so that the even entries appear first`, and in your example, there are no even entries. 

Also note that there is no order which has to be maintained within the even entries, or the odd entries in the final result.

**Comment by sagarsavla** [comment]
Oh so order is not required to be maintained. Maybe I read it wrong then. I
thought order was supposed to be maintained.

**Comment by deveshks** [comment]
> Oh so order is not required to be maintained. Maybe I read it wrong then. I thought order was supposed to be maintained.

Yep, just the even values have to appear before odd values. I think you can go ahead and close the issue as well

**Comment by sagarsavla** [comment]
Thanks for clarifying.
