### ISSUE TITLE
Adding question number prefix to file names?

### ISSUE THREAD

**Issue by asafsarid** [adnanaziz/EPIJudge#25]
Hello,
First of all I would like to say that this judge / practice system is great and really helpful! Thanks for that.
Just one suggestion. I am working with the book, and for every question I need to go to the mapping in the README in order to check which file is used for that question. I think it would be great to add a short prefix such as "q6_1_" for Question 6.1 in the book. 
That way it will also be sorted nicely in the IDE and the mapping won't really be necessary.

Thanks!

**Comment by tsunghsienlee** [comment]
Hi @asafsarid ,

Thanks for your good words, and sadly that since we change problem ordering every now and then for better organization and new problems might be added during the revisions.  So it is not feasible to add the chapter and problem index into those file.

In the next version of the book, we would like to add those inline inside the book so it will be much easier to find the file you shall focus.
