### ISSUE TITLE
Plans for relaunch of EPI Online Judge ?

### ISSUE THREAD

**Issue by magician03** [adnanaziz/EPIJudge#51]
Hi,

This book, repo are amazing and helpful. Many Thanks for it. I recently stumbled across your [website](http://elementsofprogramminginterviews.com/) and found out that you earlier had an online judge and closed it due to issues. Are there any plans to rebuild and relaunch it ? I am interested to contribute and be a part of that team.

**Comment by adnanaziz** [comment]
hi diwakar,

we'd love to build a solid online judge. now that we've got the test
framework figured out, i think we are ready to revisit that.

in terms of a minimum viable prototype, i think we'd like to have a login,
and a list of problems, in book order, with the state for each one
(completed successfully, started but failing some tests, not started).

i think the front-end can be build pretty easily in bootstrap.

on the backend, i used a noide.js server that would forward submissions
(after adding some headers/driver code) to an open source project that
would compile and run code in a docker container. this step was not very
robust, the open source project was somewhat poorly written.

i think a good starting point would be to work on the backend services,
make them very solid, then go back and add the UI (login, list of problems
to solve, state). i think the UI can be build very easily with bootstrap,
and for login, there's stuff in firebase (?) from google that can handle
simple db operations (since all we do is key-based lookup of the user's
state)

you can write to us directly via email to brainstorm some more,

bye,
adnan

**Comment by alok-sinha** [comment]
Hi Adnan,

  Have you considered GO based backend service to serve? I am interested in
contributing to backend if you are planning it in GO or Java.

  Also, is there a plan to release GO based book? I am writing the
solutions to problems in GO.

Alok

**Comment by xandfury** [comment]
Hi.
This is just a suggestion. How about using an existing online judge? Sites such as [`spoj.com`](https://www.spoj.com/) are great and very helpful for practice. You can even host a private contests - so EPI problems are exposed in a contained environment. :smile:

**Comment by adnanaziz** [comment]
We will do this some day, but there's some clear advantages of an offline judge - choose your own debugger, compiler, dev environment, editor/IDE, get complete visibility, unconstrained access (can work while commuting), more responsive. 

You also don't have the pressure of comparing your solution to the solution at the top of a leaderboard, which is not useful when prepping for an interview (since the leaderboard solutions are very very intricate, and are not realistic to present in an interview).
