### ISSUE TITLE
Test cases will not execute correctly for dutch_national_flag.py

### ISSUE THREAD

**Issue by armandosrz** [adnanaziz/EPIJudge#56]
In line 45, A is not being reassigned after the executor runs.
Solution:
```
 A = executor.run(functools.partial(dutch_flag_partition, pivot_idx, A))
```

**Comment by armandosrz** [comment]
After further review, I think this only breaks for solutions that create a new list instead of solving in place.

**Comment by metopa** [comment]
@armandosrz indeed, that is a bug. We'll fix it in the next release. Or we'll gladly accept your PR to mark your contribution. Thank you

**Comment by tsunghsienlee** [comment]
Hi @armandosrz ,

I don't see what you are referring to in https://github.com/adnanaziz/EPIJudge/blob/1e03a0c4e3ac033f1814e31c817e3a9889035aa3/epi_judge_python/dutch_national_flag.py#L22

Could you double-check this? BTW remember this problem is asking for returning a list but in-place modification.
