### ISSUE TITLE
DeadlineDetection.java

### ISSUE THREAD

**Issue by kvguarin** [adnanaziz/EPIJudge#77]
Class GraphVertex is incomplete in EPIJudge/epi_judge_java/epi/DeadlockDetection.java

It is currently: 
```
public static class GraphVertex {
    public List<GraphVertex> edges;
    public GraphVertex() { edges = new ArrayList<>(); }
  }
```

It should be:
```
  public static class GraphVertex {
    public enum Color { WHITE, GRAY, BLACK }
    public Color color;
    public List<GraphVertex> edges;
    public GraphVertex() {
      color = Color.WHITE;
      edges = new ArrayList<>();
    }
  }
```

**Comment by metopa** [comment]
@kvguarin Thank you for pointing this out. The following modification is a part of a solution, that we don't want to give away. However, it is not clear, that you're allowed to change the class definition. This will be fixed.

**Comment by tsunghsienlee** [comment]
Hi @kvguarin ,

In fact, there is no problem of the GraphVertex definition in Judge. The one given in Judge is the basic definition, and in order to solve this problem, you might enhance this with `Color` enum to solve this.

Think in the other way, in normal graph problem, a graph node would not carry the field of `Color` at all, and that is the reason we did not include that in Judge template.
