### ISSUE TITLE
Is hashCode() in BinaryTreeNode.java correct?

### ISSUE THREAD

**Issue by junhaowww** [adnanaziz/EPIJudge#98]
Hi,

Since `BinaryTreeNode` is a class for binary tree node, the data is not required to be unique. If two `BinaryTreeNodes` have the same data and children, they have the same `hash code` values.

When I was working on the brute-force solution of `problem 9.5 - Sum the root-to-paths in a binary tree`, I found that it could be an issue. Here is the detail I posted: [link](https://www.junhaow.com/lc/problems/epi/9_5-sum-root-to-leaf-paths-of-binary-tree.html).

Please refer to the `brute-force/why it fails` section. Thank you!

Junhao

**Comment by metopa** [comment]
Hi @junhaowww, 

> If two BinaryTreeNodes have the same data and children, they have the same hash code values.
I suppose this is what the current implementation does (correct me if I'm wrong). Then this is correct since 2 equal objects must have the same hash value.

I can't see your post - I just see a blank page when I follow your link.

**Comment by junhaowww** [comment]
Hi @metopa ,

Here is [the link](https://www.junhaow.com/lc/problems/tree/sum-and-path/9_5-sum-root-to-leaf-paths-of-binary-tree.html)

**Comment by metopa** [comment]
Hi @junhaowww,

On the hash code issue, the result is perfectly fine, since a hash code should be the same for the equivalent objects (not only for identical ones). So b3, b4, b5 are not the **same** trees, but they are **structurally equal** trees, thus they have the same structure and values. For your use case, you want to use identity mapping, Java has [`IdentityHashMap`](https://docs.oracle.com/javase/7/docs/api/java/util/IdentityHashMap.html).

Moreover, a hash code may be the same for different objects (easy to prove: there's an infinite number of trees, but only 2^64 possible hash values). And this fact doesn't bother `HashMap`. HashMap would work correctly even if `hashCode` would always return `0` (though it will lower performance).

Speaking about your solution, for the optimal algorithm, you don't need child->parent mapping at all. Consider calculating the sum moving from the root to leaves. If you stuck, you can take a look at our solution in `epi_jusge_java_solutions` folder.

Cheers,
Slava
